#!/bin/bash
#SBATCH --job-name binary_3M_2M_1000d
#SBATCH --time=48:00:00
#SBATCH --cpus-per-task=16
#SBATCH --ntasks=1
#SBATCH --mem=16000M
#SBATCH --account=$SLURM_ACCOUNT

set -x # enables debugging

./clear_output
./rn > log.out

scontrol show job $SLURM_JOB_ID # print out report
