#!/bin/bash
#SBATCH --job-name single_3M
#SBATCH --time=30:00:00
#SBATCH --cpus-per-task=8
#SBATCH --ntasks=1
#SBATCH --mem=12000M
#SBATCH --account=$SLURM_ACCOUNT

# source ~/.bash_profile
# source $MESASDK_ROOT/bin/mesasdk_init.sh

set -x # enables debugging
export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK # tell code how many cores

./rn > log.out 

scontrol show job=$SLURM_JOB_ID # print out report
