#!/bin/bash
#SBATCH --job-name binary_gs18
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=16
#SBATCH --ntasks=1
#SBATCH --mem=16000M
#SBATCH --account=$SLURM_ACCOUNT

set -x # enables debugging

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
source $MESASDK_ROOT/bin/mesasdk_init.sh

./clear_output
./rn

scontrol show job $SLURM_JOB_ID # print out report
seff $SLURM_JOB_ID
