#!/bin/bash


cd "$1"

JOB_NAME="$1"

sbatch <<EOT
#!/bin/bash
#SBATCH --job-name=$JOB_NAME
#SBATCH --time=24:00:00
#SBATCH --cpus-per-task=12
#SBATCH --ntasks=1
#SBATCH --mem=12000M
#SBATCH --account=$SLURM_ACCOUNT

set -x # enables debugging

cd $1

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK


./rn > log.out

scontrol show job $SLURM_JOB_ID # print out report

EOT

echo running  $JOB_NAME

cd ..
